### ISSUE TITLE
Compilation fails because of type mismatch

### ISSUE THREAD

**Issue by hardliner66** [robik/pack-d#6]
I attached a log file from the compilation with dub:
[compile_log.txt](https://github.com/robik/pack-d/files/390179/compile_log.txt)

and the source file to reproduce the problem:
[app.d.txt](https://github.com/robik/pack-d/files/390182/app.d.txt)

Environment:
OS: Windows 10
Arch: x64
dub version: 1.0.0
lib version: 1.0.0

**Comment by robik** [comment]
I've just compiled your case locally and it works just fine (`x64` too). 

Does it fix the problem if you change `reader.d:101` from:

```D
skipBytes(offset - _position);
```
to 
```D
skipBytes(cast(size_t)(offset - _position));
```

**Comment by hardliner66** [comment]
Yes it does, but couldn't this lead to problems for very big files?

Because if position is stored as long and size_t is a smaller type, the value could be truncated.

**Comment by hardliner66** [comment]
Well, I just found that Range.popFrontN only accepts size_t as argument, so I guess we have to live with this cast.

**Comment by hardliner66** [comment]
Update: forget my last comment. according to the d documentation, size_t should be big enough.

**Comment by robik** [comment]
Allright :+1:
I will commit that change now and update the DUB package.

For big files you `BinaryReader#skipBytes` should be good enough.

**Comment by hardliner66** [comment]
Everything works as expected now. Thank you very much.
